{
 "title": "Monitoring dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Backend Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sitespeed_io.default.summary.www_leanovia_com.chrome.native.browsertime.pageTimings.*.median"
    }
   ]
  },
  { "title": "Graphite Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Received data",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "carbon.agents.graphite-deployment-5c8dbbd8c6-cwgwx-a.metricsReceived"
    }
   ]
  },
  {
   "title": "Graphite CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "carbon.agents.graphite-deployment-5c8dbbd8c6-cwgwx-a.cpuUsage"
    }
   ]
  },
  {
   "title": "Graphite Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "carbon.agents.graphite-deployment-5c8dbbd8c6-cwgwx-a.memUsage"
    }
   ]
  }
 ]
}